// Generated by scripts/test-capability-manifest.mjs; do not edit.

export const GENERATED_TINYMIST_PROVIDER_ARTIFACTS = Object.freeze({
  "native": Object.freeze({
    "backendVersion": "0.15.8",
    "checksumReference": "tinymist-native-patched.sha256",
    "digest": "76a2c53911c9ac12f33113c4c647897f4fe02095196c80d8681ed446614f5f91",
    "positionEncoding": "utf-16"
  } as const),
  "web": Object.freeze({
    "backendVersion": "0.15.8",
    "checksumReference": "vendor/tinymist-0.15.8/SHA256SUMS",
    "digest": "0e651378d9351ba59d5f32e407da9e4aaccc77d9923fe740012c6b5e34cf771b",
    "positionEncoding": "utf-16"
  } as const)
} as const);

export const GENERATED_TINYMIST_PROVIDER_QUALIFICATION = Object.freeze({
  "codeActionProvider": Object.freeze({
    "classification": "host-optional",
    "native": true,
    "reason": "qualified independently by native and Web rich-provider transcripts",
    "sameOptions": true,
    "web": true
  } as const),
  "codeLensProvider": Object.freeze({
    "classification": "unavailable",
    "native": true,
    "reason": "effectful export command with resolveProvider=false",
    "sameOptions": true,
    "web": true
  } as const),
  "colorProvider": Object.freeze({
    "classification": "host-optional",
    "native": true,
    "reason": "qualified independently by native and Web rich-provider transcripts",
    "sameOptions": true,
    "web": true
  } as const),
  "completionProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web baseline transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "definitionProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web navigation transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "documentFormattingProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web rich-provider transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "documentHighlightProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web navigation transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "documentLinkProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web rich-provider transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "documentRangeFormattingProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web rich-provider transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "documentSymbolProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web navigation transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "executeCommandProvider": Object.freeze({
    "classification": "deferred",
    "native": true,
    "reason": "artifact provider options differ",
    "sameOptions": false,
    "web": true
  } as const),
  "experimental": Object.freeze({
    "classification": "deferred",
    "native": true,
    "reason": "advertised by both artifacts; method transcript not yet qualified",
    "sameOptions": true,
    "web": true
  } as const),
  "foldingRangeProvider": Object.freeze({
    "classification": "deferred",
    "native": true,
    "reason": "advertised by both artifacts; method transcript not yet qualified",
    "sameOptions": true,
    "web": true
  } as const),
  "hoverProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web baseline transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "inlayHintProvider": Object.freeze({
    "classification": "host-optional",
    "native": true,
    "reason": "qualified independently by native and Web rich-provider transcripts",
    "sameOptions": true,
    "web": true
  } as const),
  "positionEncoding": Object.freeze({
    "classification": "deferred",
    "native": true,
    "reason": "advertised by both artifacts; method transcript not yet qualified",
    "sameOptions": true,
    "web": true
  } as const),
  "referencesProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web navigation transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "renameProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web rich-provider transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "selectionRangeProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web navigation transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "semanticTokensProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web baseline transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "signatureHelpProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web baseline transcript",
    "sameOptions": true,
    "web": true
  } as const),
  "textDocumentSync": Object.freeze({
    "classification": "deferred",
    "native": true,
    "reason": "advertised by both artifacts; method transcript not yet qualified",
    "sameOptions": true,
    "web": true
  } as const),
  "workspace": Object.freeze({
    "classification": "deferred",
    "native": true,
    "reason": "advertised by both artifacts; method transcript not yet qualified",
    "sameOptions": true,
    "web": true
  } as const),
  "workspaceSymbolProvider": Object.freeze({
    "classification": "core-required",
    "native": true,
    "reason": "compatible advertisement plus checked native/Web navigation transcript",
    "sameOptions": true,
    "web": true
  } as const)
} as const);
